# Generated by Django 4.2 on 2024-01-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_username_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_add',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
